name: ${baseName}
main: ${basePackage}.${baseName}
version: ${version}
description: feeling awfully sleepy
api-version: ${apiVersion}
author: sexnine
libraries:
  - "org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}"
  - "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
  - "net.kyori:adventure-text-minimessage:4.17.0"
softdepend:
  - "ProtocolLib"
  - "AFKPlus"